### ISSUE TITLE
LTタイマーについて

### ISSUE THREAD

**Issue by vestige** [TochigiRaspberryPICircle/bm#3]
今日のメニュー
  * タイマー
  * ScratchDay＆イベント
  * BM

**Comment by vestige** [comment]
* ScratchDay2018の方針
* イベントの企画の話
* LTタイマー

**Comment by vestige** [comment]
LTタイマーの仕様
   * 時間を設定できる（30秒から60分まで）
   * のこり時間が10秒を切ったら、参加者が気が付ける仕組み
   * 時間になったら、拍手を促せる仕組み
   * 発表者の邪魔にならない
   * 発表に集中できる
   * 発表者にのこり時間がわかる
   * タイマーの開始がだれでもできるようにする

**Comment by vestige** [comment]
今回のLTタイマーは
* Timerセットする（PC側）
   * 初期表示 00:00
   * Editボタンを押したら、数値をセットできる
   * Sボタンを押したら、カウントダウン
* 起動はラズパイ のボタンで登壇者が押してもらう

**Comment by vestige** [comment]
4/7は

- ラズパイ からの起動ができるか
- のこり１０秒で見た目を変更
- 残りがゼロになったら、拍手を促すメッセージが表示される

**Comment by akimach** [comment]
時間の表示にミリ秒も表示したいです。現在のやり方だと、例えば残り時間が0.99秒でも「00:00」と表示されてしまいます。

**Comment by vestige** [comment]
あれ？残り時間は常に切り上げだよ。

**Comment by vestige** [comment]
LT Timerの仕様について（土曜日までに書く）

- start / stop / resetボタン
- 入力しやすいように、プリセットでタイマー設定ができる（たとえば、３分、５分、１０分）
  - 一般講演は8min
  - LTは2min
- 繰り返しができるモード(LT用。繰り返しのインターバルは60秒)
- 数字を大きくみせておきたい
- イベントのタイトル名を表示する
- スケジュールができるモード（残り時間と小さいタイマー）→別のアプリ感がでてきてるよくないね。
   - たとえば、このモードのときは１断面に全体の残り時間、２断面に各セッションの時間
   - 全体の時間がきたら、拍手、それ以外は拍手なし
- 拍手の音はラズパイ のスピーカーから？
- 残り１０秒になったら、ラズパイ のボタンの色は変化？


参考資料？
- MacRubyだけど、UI部分はかわっていないので参考までに
    - https://github.com/vestige/TochigiTalksTimer

**Comment by akimach** [comment]
macとRasPi3のペアリング完了
http://totech.hateblo.jp/entry/2017/01/09/121706

**Comment by vestige** [comment]
![paper 1](https://user-images.githubusercontent.com/555286/38742027-607f5508-3f76-11e8-8dc0-c327505cfa97.png)

- modeは"Normal / Panel / LT "
- Panelのときは888888のところに全体ののこり時間がでるようにする

![paper 2](https://user-images.githubusercontent.com/555286/38742033-65c18fa4-3f76-11e8-8ed2-5380647d68a2.png)

- 拍手の音はせっかくなので、ラズパイ のスピーカーから出したほうがよい？
- タイマーがうごきはじめたら、ボタンは点滅したほうがかっこよさそうだけど、こっちにもタイマー必要になっちゃうね。むずかしそう。

**Comment by akimach** [comment]
@vestige Panel / LTモードの違いは何ですか？

**Comment by vestige** [comment]
パネルはタイマーをスケジュールできるモード
LTは繰り返し2分タイマーが動きつづけるモード

**Comment by akimach** [comment]
@vestige 作ってみました。
![window](https://user-images.githubusercontent.com/17570265/39300240-ffd82a58-4985-11e8-9390-dba669a6bd67.jpg)

**Comment by akimach** [comment]
## 悩みごと1：フルスクリーン時のテキストやボタン等のパースの拡大・縮小

iOSのauto layoutと違って、画面サイズの変更に追随してテキストのサイズを変更するのが標準機能でできないようです。なので、通知センタを使ってゴリゴリ書こうする予定です。

## 悩みごと2：謎パーツ

よねざわさんの絵の**reset**ボタンの上にあるパーツって何ですか？（聞き逃してたらすみません）

Answer：「1分、3分、5分」のプリセット

**Comment by vestige** [comment]
800x600ぐらいのプロジェクターなのでそんなに大きなウィンドウじゃなくてもよいかもね。
謎パーツはタイマープリセット。ノーマルの時にあったらよいかなぁっと。

**Comment by akimach** [comment]
## 通信

* mac：`http://192.168.2.1/`（例）
* ラズパイ：`http://raspberrypi.local/`

### ラズパイ → mac

* `GET /start`：タイマーをスタートさせる
* `GET /stop`：`/start`が既に発行されタイマーが動いている場合はタイマーを一時中止

### mac → ラズパイ

* `GET /lastspurt `：残り10秒になるので、ラズパイ のボタンの色は変化させる
* `GET /finish`：終了したので音声を鳴らす

**Comment by vestige** [comment]
restartのところと、fireの中のif文がなんか引っかかるなー
タイマーのところ、クロージャでかいてるから、自分がわからないだけかな？

**Comment by akimach** [comment]
こことここですね。

> restartのところ

https://github.com/TochigiRaspberryPICircle/bm/blob/master/ReLT_Timer/hoge/LTTimer.swift#L24-L30

エラー投げるところですかね。viewcontrollerでも対処できますが、残り時間を保持していないというのはLTTimerクラスで問題を抱えてたほうがいいかなと思いました。

> fireの中のif文

https://github.com/TochigiRaspberryPICircle/bm/blob/master/ReLT_Timer/hoge/LTTimer.swift#L39-L46

確かに引っかかります。10秒以下になったら一回だけ、ラストスパートのリクエストをラズパイに送りたいのですが何かいい書き方ないですかね。

**Comment by akimach** [comment]
ViewControllerとLTimerクラスのコミュニケーションは、通知センターとプロトコルを使ったデリゲートパターンのどちらがいいのかも迷いました。iOSをみると後者のほうが一般的だな

**Comment by vestige** [comment]
https://qiita.com/KikurageChan/items/5b33f95cbec9e0d8a05f

まずはタイマーのコールバックを外にだしてみたら少しわかるのかも。

**Comment by vestige** [comment]
isRestartってなんで必要なんだっけ？

**Comment by akimach** [comment]
@vestige 

> isRestartってなんで必要なんだっけ？

確かにいらないですね。LTTimerの[remainingTime](https://github.com/TochigiRaspberryPICircle/bm/blob/master/ReLT_Timer/hoge/LTTimer.swift#L14)を拾えればそこでrestartか否か判断できます

もともとの考えとしてはスタートボタン１つで、開始とストップからの再開を兼ねるために入れました

**Comment by akimach** [comment]
アイコンを作った。

![icon_128x128 2x](https://user-images.githubusercontent.com/17570265/39368797-8a198c80-4a75-11e8-9740-5d5bf10e60f7.png)

ボタンを押したらタイマーをスタートできるようにした。

**Comment by vestige** [comment]
なかなかかわいらしいボタンねー

**Comment by vestige** [comment]
今回のイベントでタイマー使うところをまとめてみます

- 3分   ... オープニング、拍手の練習
- 8分( x 3)  ... 一般公演1
- 25分　... みどころとバグ供養
- 8分( x 6)  ... 一般公演2
- 70分 ... パネル１
   - 22分  ... 導入部分
   - 12分 x 4 ... 各お題
- 90分 ... パネル２
   - 30分...導入
   - 15分 x 4 ... 各お題
 - 2分と1分（インターバル）のタイマー ... LT用

**Comment by akimach** [comment]
* ラズパイのボタンで、macのタイマーのスタートができるようになった
* タイマー終了時に拍手もOK

**Comment by vestige** [comment]
SwifterとSwiftJSONはどうやっていれるのさー？
コードだけ確認しておくねー

**Comment by akimach** [comment]
`pod install`

**Comment by akimach** [comment]
まずCustom画面のような複数のタイマーを組合せられるような汎用的な機能・メニュー画面を作って、そこからパネル、LTに特化していくのはどうでしょうか

**Comment by akimach** [comment]
パネルディスカッション用画面をこんな感じで実装してみました。

![image](https://user-images.githubusercontent.com/17570265/39403786-f91d8fa6-4bbe-11e8-99c4-8271746daea0.png)

**Comment by akimach** [comment]
時間管理できるようにしました。タイムスケジュールのプリセットを読み込んだあと、既にある行のタイトルと時間は変更可能。

![image](https://user-images.githubusercontent.com/17570265/39460086-7d5cde66-4d3b-11e8-9329-db53f28015a4.png)

![image](https://user-images.githubusercontent.com/17570265/39460125-c7374a9e-4d3b-11e8-90ca-b742aba85bdb.png)

行の追加、削除ができるようにしたい。

**Comment by akimach** [comment]
- [x] テーブルのデータソースを別クラスに分けたい
- [x] ボタンを設けて、行の追加をできるようにしたい
- [x] ラストスパート（残り10秒）の表現が必要か否かの設定を入れたい
- [ ] Storyboard上にUIパートを詰めてつじつまを合わせている感じなので整理しておきたい（UIViewControllerとNSViewControllerの勝手が思ってたより違う）

**Comment by akimach** [comment]
ノーマル

![2018-05-01 22 40 28](https://user-images.githubusercontent.com/17570265/39474827-bc97acc8-4d90-11e8-980b-f25f4289daa9.png)

パネル

![2018-05-01 22 39 14](https://user-images.githubusercontent.com/17570265/39474826-bc684726-4d90-11e8-89fe-2a81d02754d5.png)

LT（下の画面だと2つ追加済み）

![2018-05-01 22 38 37](https://user-images.githubusercontent.com/17570265/39474825-bc3964d8-4d90-11e8-8684-0129734bfa24.png)

**Comment by akimach** [comment]
@vestige 
デモ版を用意しました。お試しをー。
https://github.com/TochigiRaspberryPICircle/bm/releases/tag/0.0.1

**Comment by vestige** [comment]
updateしたけど、ノーマルモードがスタートしないよ...
デモ版は明日（てか、今日）チェックアウトしてみるよ

**Comment by vestige** [comment]
気になること
- [x] タイマーの文字がずれる。センタリングのせい？
- [x] パネルのは設定したら、ノーマルと同じ画面でうごいて欲しい。これはやるつもりのやつかな？

**Comment by akimach** [comment]
> ノーマルモードがスタートしないよ...

確認しました。直します。

**Comment by akimach** [comment]
>  パネルのは設定したら、ノーマルと同じ画面でうごいて欲しい。これはやるつもりのやつかな？

そうなんですか。スタッフの人とか参加者もどういう流れでやるのか見えるといいのかなと思ってました。

**Comment by vestige** [comment]
5/2にやること

- LTモードはやめる
- パネルは設定画面にする
- 設定しているタイマーだけ繰り返し行えるタイマー
- 上に表示されるのは条件によって変更する
   - タイマーが複数設定されているときは全体終了の時刻にする →タイトルを設定できるようにする
   - タイマーがひとつのときは表示しない
   - どちらのときも各タイマーの残り１０秒になったら、"拍手の準備を"
   - タイマーが0になったら、"888888" 
   - 複数のタイマーがセットされているときは、"888888"のまま、10秒あけて、次のタイマーを動かす

**Comment by vestige** [comment]
やりとりが煩雑かもしれないので、ディスカッションおこした。
https://github.com/orgs/TochigiRaspberryPICircle/teams/bm/discussions

**Comment by vestige** [comment]
![paper 3](https://user-images.githubusercontent.com/555286/39501136-0b0960fa-4df4-11e8-8a20-01c11e5f7f94.png)

- messageの振る舞いは上に書いたように自由に文字が設定できる（全角10文字まで）
   - ex) 12:45まで
- messageは残り１０秒で"拍手の準備を"
- messageは残り０秒で"888888"

![paper 4](https://user-images.githubusercontent.com/555286/39501138-0dd7e964-4df4-11e8-8397-24aace2547a9.png)

こんな感じでどかな？

**Comment by akimach** [comment]
やり方が2つあると思います

* 同一画面上で、上の二つのビューを担う
  * ViewControllerが１つ、今のやり方と同じ
  * OK、Cancelボタンが不要
  * 右下のSettingsで遷移
* 設定画面は別のウィンドウ
  * Settingボタン → 設定画面が開く → OKボタン → 設定画面を閉じる
  * ViewControllerを2つにするので、VC間でシングルトンかなんかで変数を共有できるようにする必要がある

前者のほうでやりたいのですがいいですか

**Comment by vestige** [comment]
Restart機能は今回やらない
Stopボタンを削除する

**Comment by vestige** [comment]
画面の切り替え方法は木村くんが実装しやすい方でいいですよ。
UI的にはどちらでも構わないですー

**Comment by akimach** [comment]
いまこんな感じです。メッセージのところは欠けていて、タイトルのが表示されます。

[hoge.app.zip](https://github.com/TochigiRaspberryPICircle/bm/files/1966351/hoge.app.zip)

明日つづきやるです

**Comment by akimach** [comment]
> 複数のタイマーがセットされているときは、"888888"のまま、10秒あけて、次のタイマーを動かす

をやろう

**Comment by akimach** [comment]
> タイマーが複数設定されているときは全体終了の時刻にする →タイトルを設定できるようにする
> タイマーがひとつのときは表示しない

別に機能として実装しないで、設定画面でtitleを単に空文字列にすれば気がします。

**Comment by akimach** [comment]
[せきさんに作ってもらった画像](https://twitter.com/m_seki/status/991867955662110720)、入れておきます

**Comment by vestige** [comment]
いまさらだけど、画面の大きさどうしようね。
800x600ぐらいはあった方がいいような。

**Comment by akimach** [comment]
レスポンシブにする予定です

**Comment by akimach** [comment]
初期画面を変更、計測終了時にライオンの画像を表示するようにしました。

[hoge.app.zip](https://github.com/TochigiRaspberryPICircle/bm/files/1976659/hoge.app.zip)

**Comment by akimach** [comment]
[hoge.app.zip](https://github.com/TochigiRaspberryPICircle/bm/files/1976748/hoge.app.zip)

**Comment by vestige** [comment]
- StartとStopのボタンの状態がおかしくなることがある。なんだろう。
    - 設定でいじっていたら、おかしくなった。
    - Start -> Stop -> Start -> StopでStopしなくなった。
- Resetボタンがsettingの中にあるよ。コミットしたものが違う？
- 拡大が縦にしか伸びないのはそういうもの？（横にものびるのかと思っていた）

**Comment by vestige** [comment]
これなんだ？このコードがなんか変な感じする

https://github.com/TochigiRaspberryPICircle/bm/blob/c01acfdfb312c4ef2225a769c01f385f724b7b47/ReLT_Timer/hoge/ViewController.swift#L170

**Comment by akimach** [comment]
LTTimer.swiftのほうがだと思います。

**Comment by akimach** [comment]
> Resetボタンがsettingの中にあるよ。コミットしたものが違う？

勝手に書いた別のresetボタンです。これは複数タイマーをいくつか進めてしまった時、インデックスをリセットするためのものです。

**Comment by akimach** [comment]
リスタートで動かして

https://github.com/TochigiRaspberryPICircle/bm/blob/c01acfdfb312c4ef2225a769c01f385f724b7b47/ReLT_Timer/hoge/ViewController.swift#L126

ここでもキックしてるからおかしい

https://github.com/TochigiRaspberryPICircle/bm/blob/c01acfdfb312c4ef2225a769c01f385f724b7b47/ReLT_Timer/hoge/ViewController.swift#L136

別オブジェクトとしてタイマーを発行してるから参照がすり替わり管理できなくなって止められなくなった、と思います。

あータイマーはシングルトンで保持しとかないと危ないのかな

**Comment by akimach** [comment]
> 拡大が縦にしか伸びないのはそういうもの？（横にものびるのかと思っていた）

これはあとでやります。

**Comment by akimach** [comment]
トグルでNormal押して、settingを選ばず、Normalを選ぶともう一度startが発行できてこれも止められなく

**Comment by akimach** [comment]
[hoge.app.zip](https://github.com/TochigiRaspberryPICircle/bm/files/1977544/hoge.app.zip)

**Comment by akimach** [comment]
[hoge.app.zip](https://github.com/TochigiRaspberryPICircle/bm/files/1977646/hoge.app.zip)

**Comment by akimach** [comment]
こんな感じで。

![2018-05-10 15 44 59](https://user-images.githubusercontent.com/17570265/39856113-ad78c864-5469-11e8-987e-34e6b19c5996.png)
![2018-05-10 15 45 19](https://user-images.githubusercontent.com/17570265/39856114-ada7b368-5469-11e8-9e90-c191f8233677.png)
![2018-05-10 15 45 36](https://user-images.githubusercontent.com/17570265/39856116-add26b94-5469-11e8-8dae-4a5f057bd6c6.png)
![2018-05-10 15 45 42](https://user-images.githubusercontent.com/17570265/39856117-ae0043e8-5469-11e8-9308-3e2a60a0d116.png)

**Comment by akimach** [comment]
50e110c まで取り入れた最新版です。

[hoge.app.zip](https://github.com/TochigiRaspberryPICircle/bm/files/1995579/hoge.app.zip)

**Comment by vestige** [comment]
さわってみたよー。タイマー中にsetting押せちゃうのはちょっとだけど、良い感じー♩

**Comment by akimach** [comment]
@vestige ありがとうございます！

**Comment by akimach** [comment]
![dcpscsxvaaaryh8](https://user-images.githubusercontent.com/17570265/39950578-13d61694-55bd-11e8-950a-6e0534355d90.png)

**Comment by vestige** [comment]
イベントがおわったので、クローズするねー。おつかれさまー！

**Comment by akimach** [comment]
お疲れ様でした！
